### PR TITLE
Update cait datasets

### PR DESCRIPTION
**Pull request by pabloarosado**
* Create a script to download and prepare CAIT datasets.
* Add a generic module for sanity checks.
* Add script to run sanity checks on CAIT datasets.
* Create a script to upload CO2 dataset files to S3.
* Update the main script to generate CO2 dataset files.
* Add CAIT dataset files to repos (in a new "grapher" folder).
* Update the CO2 dataset csv file and codebook, and remove the json and xlsx files (they will be hosted only in S3).
* Update README (to have links to the CO2 dataset files in S3).

### CODE REVIEW

**Review by HannahRitchie — APPROVED** [review]
All looks good to me. Thanks @pabloarosado!

**Review by bnjmacdonald — COMMENTED** [review]
great @pabloarosado! Though I do have a question about the data pipeline, which I'm a little confused about here.

Looks like the data flow is:

(1) `prepare_cait_datasets.py` downloads the data and saves it as csv --> 
(2) then you've manually uploaded these csv files to the grapher db --> 
(3) then `main.py` retrieves the uploaded variables from the grapher DB in order to construct the merged csv that is then uploaded to s3 for public consumption.

If so, then it looks like `prepare_cait_datasets.py` should be removed from this PR and instead included as part of a PR in `importers` or `etl` that implements a bulk import for this CAIT data. 

Main reason is that the inclusion of `prepare_cait_datasets.py` in this `co2-data` repo means that the repo is both a *source* of data that goes into the grapher DB as well as a *consumer* of data that is already in the grapher DB, which creates confusion about the ultimate source of truth.

**Comment by pabloarosado** [comment]
Thanks @bnjmacdonald, I was trying to follow the philosophy of the [energy-data](https://github.com/owid/energy-data) repos. But I agree with you that it would be better to use importers or etl to upload the CAIT datasets to grapher. I could either do it now and cancel this PR, or leave it for a future improvement. I don't have a strong opinion on which option is better, @edomt ?

**Comment by edomt** [comment]
Indeed the general pipeline isn't optimal – but of course, it was already like that before. There are several things to take into account, including that:
- `importers` will be deprecated in the coming months
- `etl` isn't fully ready yet, so even an implementation of this pipeline in `etl` would need to be revisited at some point
- there are a lot of outstanding & high-priority datasets to deal with.

What I would suggest to get rid of the confusion mentioned by @bnjmacdonald is that:
- we move `prepare_cait_datasets.py` & its output into a `cait` folder in `importers` in its current state, i.e. without refactoring it as a "true" importer that upserts data into Grapher (because that part will be deprecated soon). So something that looks like the [population](https://github.com/owid/importers/tree/master/population) folder.
- The output of that script is then manually uploaded to Grapher
- `main.py` in this co2 repo then fetches that Grapher dataset to use it

And at the next update of CAIT (presumably next year?), we'll transform the whole thing into a proper `etl` pipeline.

Let me know what you think :)

**Review by edomt — CHANGES_REQUESTED** [review]
See https://github.com/owid/co2-data/pull/24#issuecomment-1048703690

**Review by edomt — APPROVED** [review]
Great work, thank you Pablo!

**Pull request merged**
